service: kpi-dashboard-service

frameworkVersion: '3'
useDotenv: true
configValidationMode: error

package:
  artifact: build/kip-dashboard/kip-dashboard.zip

plugins:
  - serverless-dotenv-plugin

custom:
  apiKey-dev: da39a3ee5e6b4b0d3255bfef95601890afd80709
  apiKey-prod: 3da541559918a808c2402bba5012f6c60b27661c
  
provider:
  name: aws
  httpApi:
    payload: '2.0'
    cors: true
    # Use provided.al2 if you build with M1, provided if you build with x86_64
  runtime: provided.al2
  architecture: arm64

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  profile: fuzztival
  
  environment:
    openSearchEndpoint: ${env:openSearchEndpoint}
    openSearchUsername: ${env:openSearchUsername}
    openSearchPassword: ${env:openSearchPassword}
    ENTRYPOINT_URL: https://mogzv5pkef.execute-api.us-west-2.amazonaws.com/dev
    AWS_ACCESS_KEY_ID1: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY1: ${env:AWS_SECRET_ACCESS_KEY}
    DEPLOYED_URL: ${env:DEPLOYED_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    SEND_GRID_API_KEY: ${env:SEND_GRID_API_KEY}
    
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - es:ESHttpPost
            - es:ESHttpPut
          Resource: "*"


functions:
  http:
    handler: handle
    memorySize: 1024
    timeout: 30
    events:
        - httpApi: '*'


